menu:
  Home: /
  Archives: /archives
  About: /about/
  RSS: /feed.xml
#If you dont want it, just comment it out
# weibo: yourweibo
github: https://github.com/tumayouzi
# linkedin: yourlinkedin
# email: mailto:youremail

#Put into /source
avator: avator.jpg

favicon: /favicon.png